name: "Hello World"
description: "Greet someone"
inputs:
  who-to-greet: # id of the input
    description: "Greet"
    required: true
    default: "world"

runs:
  using: "composite"
  steps:
    - name: Set Github Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run hello.sh
      run: hello.sh
      shell: bash

    - name: Set Greeting
      run: echo "Hello ${{ inputs.who-to-greet }}."
      shell: bash

    - name: Run goodbye.sh
      run: goodbye.sh
      shell: bash
